- name: Detecting GPU
  apt:
    name: pciutils
    state: present

# test if we can find an nvidia device
- shell: lspci| grep -i nvidia
  register: stdout
  ignore_errors: yes

# gpu case
- set_fact:
    has_gpu: yes
    c_device_request:
    - driver: nvidia
      count: -1
      capabilities:
      - - gpu
        - utility
      # See https://github.com/NVIDIA/nvidia-container-runtime#supported-driver-capabilities
      # for a list of capabilities supported by the nvidia driver
    c_env:
        HOST_PROC: "/rootfs/proc"
        HOST_SYS: "/rootfs/sys"
        NVIDIA_VISIBLE_DEVICES: "all"
  when:
  - stdout is defined
  - stdout.rc == 0

# non gpu case (default)
- set_fact:
    has_gpu: no
    c_device_request: []
    c_env:
        HOST_PROC: "/rootfs/proc"
        HOST_SYS: "/rootfs/sys"
  when: stdout is not defined or stdout.rc != 0

# Install the nvidia container runtime
# from https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html#setting-up-nvidia-container-toolkit
- name: Installing nvidia-container-toolkit
  shell: >
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) &&
    curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add - &&
    curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list &&
    apt install -y nvidia-docker2 &&
    service docker restart
  when: has_gpu