before_script:
  - python -V               # Print out python version for debugging

python3.6:
  image: python:3.6
  stage: test
  script:
  - pip install tox
  - tox -e py36 pep8

python2.7:
  image: python:2.7
  stage: test
  script:
  - pip install tox
  - tox -e py27 pep8
