#### Entering th release zone
package:
    stage: package
    only: 
        - tags
    image: python3.6
    script:
    - python setup.py bdist_wheel --universal
    artifacts:
        paths:
        - dist/

publish:
    stage: deploy
    image: python3.6
    dependencies:
    - package
    script:
        - pip install twine
        # credentials are set in the env by gitlab
        - twine upload dist/* --repository-url https://test.pypi.org 