python3.5:
    image: python:3.5
    stage: test
    script:
    - pip install tox
    - tox -e py35 pep8

python2.7:
    image: python:2.7
    stage: test
    script:
    - pip install tox
    - tox -e py27 pep8

python3.6:
    image: python:3.6
    stage: test
    script:
    - pip install tox
    - tox -e py36 pep8

doc:
    image: python:3.6
    stage: test
    script:
    - pip install tox
    - tox -e docs
    artifacts:
        paths:
        - docs/_build/html

pages:
    
    stage: deploy
    dependencies:
    - doc
    script:
    - mkdir public
    - echo "hello" > pubic/index.htm
    artifacts:
      paths:
      - docs/_build/html